"""add human support ticket timestamps

Revision ID: 3033de981a75
Revises: 8571974d8114
Create Date: 2026-09-25 11:36:56.806035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3033de981a75'
down_revision: Union[str, Sequence[str], None] = '8571974d8114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('support_tickets', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    op.add_column('support_tickets', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'last_message_at')
    op.drop_column('support_tickets', 'escalated_at')
    op.drop_column('support_tickets', 'assigned_at')
    # ### end Alembic commands ###
